using System;
using System.Collections.Generic;

namespace OrderService.Domain.Models
{
    /// <summary>
    /// Domain entity representing a customer order.
    /// Contains business logic for order lifecycle transitions.
    /// </summary>
    public class Order
    {
        /// <summary>Unique identifier generated by MongoDB (ObjectId as string).</summary>
        public required string Id { get; set; }

        /// <summary>Display name of the user who placed the order.</summary>
        public required string UserName { get; set; }

        /// <summary>Line items included in the order.</summary>
        public List<OrderItem> Items { get; set; } = new();

        /// <summary>Current lifecycle status of the order.</summary>
        public required OrderStatus Status { get; set; }

        /// <summary>UTC timestamp indicating when the order was created.</summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Optimistic concurrency version. Incremented on each update.
        /// Used to detect conflicts when multiple clients modify the same order.
        /// </summary>
        public int Version { get; set; } = 1;

        /// <summary>
        /// Determines whether the order can transition to <see cref="OrderStatus.Canceled"/>.
        /// </summary>
        /// <returns>
        /// <c>true</c> if the order is not already <see cref="OrderStatus.Delivered"/>
        /// or <see cref="OrderStatus.Canceled"/>; otherwise <c>false</c>.
        /// </returns>
        public bool CanBeCanceled()
        {
            return Status != OrderStatus.Delivered && Status != OrderStatus.Canceled;
        }
    }
}
